[package]
name = "nostd_error"
version = "0.1.0"
edition = "2021"

[dependencies]
snafu = { version = "0.8.5", default-features = false, features = [
    "rust_1_81",
] }
thiserror = { version = "2.0.9", default-features = false }

[profile.release]
opt-level = "z"
lto = true
